### ISSUE TITLE
question about random_map and id_offset

### ISSUE THREAD

**Issue by ChrisMii** [anananan116/MBGen#2]
Great and fascinating work！And I have two questions: 
1) what is the use of "random_map"?  can i use hash map or other mapping to work the same way?  
2) what is "id_offset" for? And is there any special design for id_offset?

Thanks!

**Comment by anananan116** [comment]
Thanks for your interest in this project.

1. Since the item IDs are assigned based on the order that they appear in the dataset, it may introduce an unwanted prior when generating CID. For example, the first item sequence in the dataset might be 1 2 3 4 5..., which is tokenized into very similar multi-digit ids when being processed by CID tokenizer. Some similar issues are discussed here: https://github.com/jeykigung/P5/pull/3 https://arxiv.org/abs/2305.06569 . Random_map is simply a random shuffle of item ids to make sure they don't carry any information of the order of their appearance in the dataset for fair comparison. I don't think hash map would work in this case, but any random shuffle of item ids is fine.
2. id_offset reserve space for special tokens, e.g., behavior tokens, <BOS>... It is the offset that's added to all item tokens to avoid collision with special tokens.
