### ISSUE TITLE
Reproducing the HSTU Model

### ISSUE THREAD

**Issue by ykning2000** [anananan116/MBGen#7]
Hi,
I am currently working on reproducing the HSTU model as described in your recent publication. I wanted to ask if you have any available code or resources that could assist in accurately replicating your results.
Any guidance or available materials would be immensely helpful.

**Comment by anananan116** [comment]
Thanks for your interest. As mentioned in the paper, we reproduce the HSTU model by only incorporating their item, behavior tokenizer. We used the same T5 Encoder-Decoder model instead of the specially designed Transformer model in HSTU for fair comparison of tokenizers. We are not planning to release codes for baselines and ablations for now, but very simple modification to the existing tokenizer should reproduce our version of reproduced HSTU.

**Comment by ykning2000** [comment]
> Thanks for your interest. As mentioned in the paper, we reproduce the HSTU model by only incorporating their item, behavior tokenizer. We used the same T5 Encoder-Decoder model instead of the specially designed Transformer model in HSTU for fair comparison of tokenizers. We are not planning to release codes for baselines and ablations for now, but very simple modification to the existing tokenizer should reproduce our version of reproduced HSTU.

Thank you for your response. Based on my understanding, your reproduction of HSTU actually involves controlling the reverse_bt configuration to switch the order of the behavior_token and item_token. Is my understanding correct?

**Comment by anananan116** [comment]
Yes, that's what we did.
